version: '3.8'

services:
  itmo-bot:
    build: .
    container_name: itmo-ai-chatbot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge